# config.yaml

# The profile settings
slurm:
  # Default values for SLURM commands
  slurm:
    # SLURM job options
    partition: 'default'
    nodes: 1
    ntasks-per-node: 1
    cpus-per-task: 1
    mem: '1G'
    time: '00:10:00'
    
  # SLURM cluster settings
  cluster:
    # The command to submit a job
    command: 'sbatch'
    
    # The command to check the status of a job
    status: 'squeue -j {job_id}'
    
    # The command to cancel a job
    cancel: 'scancel {job_id}'
    
    # The command to get information about job nodes
    nodes: 'scontrol show hostname {job_id}'
    
  # Default job submission settings
  default:
    # Number of jobs to submit simultaneously
    jobs: 100
    # Maximum number of threads for each job
    max_threads: 8

  # Custom environment settings
  env:
    # Path to the Conda environment to activate
    conda_env: 'your_snakemake_env'
    
    # Path to the Conda executable
    conda_executable: '/path/to/conda'
    
    # Path to the Conda configuration file
    conda_config: '/path/to/conda/config.yaml'

# Additional settings
additional:
  # Path to the Snakefile
  snakefile: 'Snakefile'
  
  # Path to the static nodes script
  static_nodes_script: 'staticnodes.sh'
