# Snakefile to create input files and process them across 5 static nodes

# Define the number of threads for parallel jobs
threads: 1

# Rule to generate all required input files
rule generate_input_files:
    output:
        expand("input_file_{i}.txt", i=range(1, 6))  # Creates 5 input files
    shell:
        """
        for i in {1..5}; do
            echo "This is input file $i" > input_file_$i.txt
        done
        """

# Rule to define all output files expected
rule all:
    input:
        expand("output_file_{i}.txt", i=range(1, 6))  # Expecting 5 output files

# Rule to process each file
rule process_files:
    input:
        "input_file_{i}.txt"  # Input files generated by the previous rule
    output:
        "output_file_{i}.txt"
    resources:
        mem="4G",  # Example of memory resource
        nodes=1   # Each job will run on 1 node
    threads: 1
    shell:
        """
        echo "Processing {input}" > {output}
        sleep 10  # Simulate processing
        echo "Completed processing {input}" >> {output}
        """

# Define the order of rule execution
workflow:
    # Ensure input files are generated before processing
    generate_input_files >> process_files
