# Snakefile to create input files and process them across 5 static nodes

# Rule to generate all required input files
rule generate_input_files:
    output:
        expand("input_file_{i}.txt", i=range(1, 6))  # Creates 5 input files
    shell:
        """
        for i in $(seq 1 5); do
            echo "This is input file $i" > input_file_$i.txt
        done
        """

# Rule to define all output files expected
rule all:
    input:
        expand("output_file_{i}.txt", i=range(1, 6))  # Expecting 5 output files

# Rule to process each file
rule process_files:
    input:
        "input_file_{i}.txt"  # Input files generated by the previous rule
    output:
        "output_file_{i}.txt"
    resources:
        mem_mb=4000,  # Example of memory resource in MB
        nodes=1   # Each job will run on 1 node
    threads: 1
    shell:
        """
        echo "Processing {input}" > {output}
        sleep 60  # Simulate a longer processing time (1 minute)
        echo "Completed processing {input}" >> {output}
        """
