workflow_name: "Parallel Workflow Test"
input_dir: "input_data/"
output_dir: "output_data/"

# SLURM-specific configuration
slurm_partition: "queue-1"
num_nodes: 5
tasks_per_node: 1
time_limit: "01:00:00"

# Resources
resources:
  default_threads: 16
  default_memory: 8GB
  max_jobs: 80

# Logging
log_dir: "logs/"
latency_wait: 60
